"""Embedded synthetic workforce (50 employees) so the deployed app needs no data file.
Regenerate with app/sehim_api.py then re-embed."""

WORKFORCE = [{'employeeId': 'E10000',
  'department': 'Research & Development',
  'jobTitle': 'Laboratory Technician',
  'sapFields': {'perPersonal.gender': 'Male',
                'perPerson.age': 36,
                'empJob.department': 'Research & Development',
                'empJob.jobTitle': 'Laboratory Technician',
                'empJob.payGrade': 1,
                'timeManagement.overtimeFlag': 0,
                'empPayCompRecurring.monthlyIncome': 3210,
                'empEmployment.yearsAtCompany': 15},
  'riskScores': {'burnout': 0.003, 'mentalHealth': 0.025, 'attrition': 0.006},
  'cbri': 0.01,
  'riskLevel': 'Low',
  'topFactors': [{'factor': 'high workload / resource demand', 'direction': 'decreases'},
                 {'factor': 'workload relative to seniority', 'direction': 'decreases'},
                 {'factor': 'seniority level', 'direction': 'decreases'}],
  'explanationNarrative': 'Low burnout risk (0%). The risk is driven primarily by high workload / resource demand. No '
                          'action indicated; continue routine support.',
  'recommendedAction': 'No action indicated; continue routine support.'},
 {'employeeId': 'E10001',
  'department': 'Research & Development',
  'jobTitle': 'Laboratory Technician',
  'sapFields': {'perPersonal.gender': 'Male',
                'perPerson.age': 36,
                'empJob.department': 'Research & Development',
                'empJob.jobTitle': 'Laboratory Technician',
                'empJob.payGrade': 1,
                'timeManagement.overtimeFlag': 0,
                'empPayCompRecurring.monthlyIncome': 3210,
                'empEmployment.yearsAtCompany': 15},
  'riskScores': {'burnout': 0.002, 'mentalHealth': 0.038, 'attrition': 0.006},
  'cbri': 0.013,
  'riskLevel': 'Low',
  'topFactors': [{'factor': 'high workload / resource demand', 'direction': 'decreases'},
                 {'factor': 'seniority level', 'direction': 'decreases'},
                 {'factor': 'workload relative to seniority', 'direction': 'decreases'}],
  'explanationNarrative': 'Low burnout risk (0%). The risk is driven primarily by high workload / resource demand. No '
                          'action indicated; continue routine support.',
  'recommendedAction': 'No action indicated; continue routine support.'},
 {'employeeId': 'E10002',
  'department': 'Research & Development',
  'jobTitle': 'Research Scientist',
  'sapFields': {'perPersonal.gender': 'Female',
                'perPerson.age': 35,
                'empJob.department': 'Research & Development',
                'empJob.jobTitle': 'Research Scientist',
                'empJob.payGrade': 1,
                'timeManagement.overtimeFlag': 0,
                'empPayCompRecurring.monthlyIncome': 2977,
                'empEmployment.yearsAtCompany': 4},
  'riskScores': {'burnout': 0.007, 'mentalHealth': 0.05, 'attrition': 0.01},
  'cbri': 0.021,
  'riskLevel': 'Low',
  'topFactors': [{'factor': 'high workload / resource demand', 'direction': 'decreases'},
                 {'factor': 'seniority level', 'direction': 'decreases'},
                 {'factor': 'workload relative to seniority', 'direction': 'increases'}],
  'explanationNarrative': 'Low burnout risk (1%). The risk is driven primarily by workload relative to seniority. No '
                          'action indicated; continue routine support.',
  'recommendedAction': 'No action indicated; continue routine support.'},
 {'employeeId': 'E10003',
  'department': 'Sales',
  'jobTitle': 'Sales Executive',
  'sapFields': {'perPersonal.gender': 'Male',
                'perPerson.age': 32,
                'empJob.department': 'Sales',
                'empJob.jobTitle': 'Sales Executive',
                'empJob.payGrade': 2,
                'timeManagement.overtimeFlag': 0,
                'empPayCompRecurring.monthlyIncome': 4465,
                'empEmployment.yearsAtCompany': 3},
  'riskScores': {'burnout': 0.005, 'mentalHealth': 0.049, 'attrition': 0.013},
  'cbri': 0.02,
  'riskLevel': 'Low',
  'topFactors': [{'factor': 'high workload / resource demand', 'direction': 'decreases'},
                 {'factor': 'workload relative to seniority', 'direction': 'decreases'},
                 {'factor': 'seniority level', 'direction': 'decreases'}],
  'explanationNarrative': 'Low burnout risk (1%). The risk is driven primarily by high workload / resource demand. No '
                          'action indicated; continue routine support.',
  'recommendedAction': 'No action indicated; continue routine support.'},
 {'employeeId': 'E10004',
  'department': 'Research & Development',
  'jobTitle': 'Research Scientist',
  'sapFields': {'perPersonal.gender': 'Female',
                'perPerson.age': 28,
                'empJob.department': 'Research & Development',
                'empJob.jobTitle': 'Research Scientist',
                'empJob.payGrade': 1,
                'timeManagement.overtimeFlag': 0,
                'empPayCompRecurring.monthlyIncome': 3591,
                'empEmployment.yearsAtCompany': 3},
  'riskScores': {'burnout': 0.006, 'mentalHealth': 0.052, 'attrition': 0.011},
  'cbri': 0.021,
  'riskLevel': 'Low',
  'topFactors': [{'factor': 'high workload / resource demand', 'direction': 'decreases'},
                 {'factor': 'workload relative to seniority', 'direction': 'decreases'},
                 {'factor': 'seniority level', 'direction': 'decreases'}],
  'explanationNarrative': 'Low burnout risk (1%). The risk is driven primarily by high workload / resource demand. No '
                          'action indicated; continue routine support.',
  'recommendedAction': 'No action indicated; continue routine support.'},
 {'employeeId': 'E10005',
  'department': 'Research & Development',
  'jobTitle': 'Laboratory Technician',
  'sapFields': {'perPersonal.gender': 'Female',
                'perPerson.age': 39,
                'empJob.department': 'Research & Development',
                'empJob.jobTitle': 'Laboratory Technician',
                'empJob.payGrade': 1,
                'timeManagement.overtimeFlag': 0,
                'empPayCompRecurring.monthlyIncome': 2232,
                'empEmployment.yearsAtCompany': 3},
  'riskScores': {'burnout': 0.005, 'mentalHealth': 0.047, 'attrition': 0.012},
  'cbri': 0.019,
  'riskLevel': 'Low',
  'topFactors': [{'factor': 'high workload / resource demand', 'direction': 'decreases'},
                 {'factor': 'workload relative to seniority', 'direction': 'decreases'},
                 {'factor': 'seniority level', 'direction': 'decreases'}],
  'explanationNarrative': 'Low burnout risk (1%). The risk is driven primarily by high workload / resource demand. No '
                          'action indicated; continue routine support.',
  'recommendedAction': 'No action indicated; continue routine support.'},
 {'employeeId': 'E10006',
  'department': 'Human Resources',
  'jobTitle': 'Human Resources',
  'sapFields': {'perPersonal.gender': 'Male',
                'perPerson.age': 30,
                'empJob.department': 'Human Resources',
                'empJob.jobTitle': 'Human Resources',
                'empJob.payGrade': 1,
                'timeManagement.overtimeFlag': 0,
                'empPayCompRecurring.monthlyIncome': 2064,
                'empEmployment.yearsAtCompany': 5},
  'riskScores': {'burnout': 0.009, 'mentalHealth': 0.053, 'attrition': 0.019},
  'cbri': 0.024,
  'riskLevel': 'Low',
  'topFactors': [{'factor': 'high workload / resource demand', 'direction': 'decreases'},
                 {'factor': 'seniority level', 'direction': 'decreases'},
                 {'factor': 'workload relative to seniority', 'direction': 'increases'}],
  'explanationNarrative': 'Low burnout risk (1%). The risk is driven primarily by workload relative to seniority. No '
                          'action indicated; continue routine support.',
  'recommendedAction': 'No action indicated; continue routine support.'},
 {'employeeId': 'E10007',
  'department': 'Research & Development',
  'jobTitle': 'Laboratory Technician',
  'sapFields': {'perPersonal.gender': 'Male',
                'perPerson.age': 30,
                'empJob.department': 'Research & Development',
                'empJob.jobTitle': 'Laboratory Technician',
                'empJob.payGrade': 2,
                'timeManagement.overtimeFlag': 0,
                'empPayCompRecurring.monthlyIncome': 3072,
                'empEmployment.yearsAtCompany': 12},
  'riskScores': {'burnout': 0.03, 'mentalHealth': 0.116, 'attrition': 0.019},
  'cbri': 0.054,
  'riskLevel': 'Low',
  'topFactors': [{'factor': 'high workload / resource demand', 'direction': 'decreases'},
                 {'factor': 'seniority level', 'direction': 'decreases'},
                 {'factor': 'no work-from-home option', 'direction': 'decreases'}],
  'explanationNarrative': 'Low burnout risk (3%). The risk is driven primarily by high workload / resource demand. No '
                          'action indicated; continue routine support.',
  'recommendedAction': 'No action indicated; continue routine support.'},
 {'employeeId': 'E10008',
  'department': 'Research & Development',
  'jobTitle': 'Manufacturing Director',
  'sapFields': {'perPersonal.gender': 'Male',
                'perPerson.age': 42,
                'empJob.department': 'Research & Development',
                'empJob.jobTitle': 'Manufacturing Director',
                'empJob.payGrade': 2,
                'timeManagement.overtimeFlag': 0,
                'empPayCompRecurring.monthlyIncome': 4434,
                'empEmployment.yearsAtCompany': 9},
  'riskScores': {'burnout': 0.015, 'mentalHealth': 0.097, 'attrition': 0.017},
  'cbri': 0.04,
  'riskLevel': 'Low',
  'topFactors': [{'factor': 'high workload / resource demand', 'direction': 'decreases'},
                 {'factor': 'workload relative to seniority', 'direction': 'decreases'},
                 {'factor': 'seniority level', 'direction': 'decreases'}],
  'explanationNarrative': 'Low burnout risk (1%). The risk is driven primarily by high workload / resource demand. No '
                          'action indicated; continue routine support.',
  'recommendedAction': 'No action indicated; continue routine support.'},
 {'employeeId': 'E10009',
  'department': 'Sales',
  'jobTitle': 'Sales Executive',
  'sapFields': {'perPersonal.gender': 'Male',
                'perPerson.age': 38,
                'empJob.department': 'Sales',
                'empJob.jobTitle': 'Sales Executive',
                'empJob.payGrade': 3,
                'timeManagement.overtimeFlag': 0,
                'empPayCompRecurring.monthlyIncome': 10609,
                'empEmployment.yearsAtCompany': 16},
  'riskScores': {'burnout': 0.032, 'mentalHealth': 0.084, 'attrition': 0.022},
  'cbri': 0.046,
  'riskLevel': 'Low',
  'topFactors': [{'factor': 'high workload / resource demand', 'direction': 'decreases'},
                 {'factor': 'workload relative to seniority', 'direction': 'decreases'},
                 {'factor': 'no work-from-home option', 'direction': 'decreases'}],
  'explanationNarrative': 'Low burnout risk (3%). The risk is driven primarily by high workload / resource demand. No '
                          'action indicated; continue routine support.',
  'recommendedAction': 'No action indicated; continue routine support.'},
 {'employeeId': 'E10010',
  'department': 'Human Resources',
  'jobTitle': 'Manager',
  'sapFields': {'perPersonal.gender': 'Male',
                'perPerson.age': 56,
                'empJob.department': 'Human Resources',
                'empJob.jobTitle': 'Manager',
                'empJob.payGrade': 5,
                'timeManagement.overtimeFlag': 0,
                'empPayCompRecurring.monthlyIncome': 19717,
                'empEmployment.yearsAtCompany': 7},
  'riskScores': {'burnout': 0.03, 'mentalHealth': 0.137, 'attrition': 0.02},
  'cbri': 0.06,
  'riskLevel': 'Low',
  'topFactors': [{'factor': 'high workload / resource demand', 'direction': 'decreases'},
                 {'factor': 'workload relative to seniority', 'direction': 'decreases'},
                 {'factor': 'no work-from-home option', 'direction': 'decreases'}],
  'explanationNarrative': 'Low burnout risk (3%). The risk is driven primarily by high workload / resource demand. No '
                          'action indicated; continue routine support.',
  'recommendedAction': 'No action indicated; continue routine support.'},
 {'employeeId': 'E10011',
  'department': 'Sales',
  'jobTitle': 'Sales Executive',
  'sapFields': {'perPersonal.gender': 'Male',
                'perPerson.age': 35,
                'empJob.department': 'Sales',
                'empJob.jobTitle': 'Sales Executive',
                'empJob.payGrade': 3,
                'timeManagement.overtimeFlag': 0,
                'empPayCompRecurring.monthlyIncome': 7823,
                'empEmployment.yearsAtCompany': 10},
  'riskScores': {'burnout': 0.031, 'mentalHealth': 0.16, 'attrition': 0.023},
  'cbri': 0.068,
  'riskLevel': 'Low',
  'topFactors': [{'factor': 'high workload / resource demand', 'direction': 'decreases'},
                 {'factor': 'seniority level', 'direction': 'decreases'},
                 {'factor': 'length of service', 'direction': 'decreases'}],
  'explanationNarrative': 'Low burnout risk (3%). The risk is driven primarily by high workload / resource demand. No '
                          'action indicated; continue routine support.',
  'recommendedAction': 'No action indicated; continue routine support.'},
 {'employeeId': 'E10012',
  'department': 'Research & Development',
  'jobTitle': 'Research Scientist',
  'sapFields': {'perPersonal.gender': 'Female',
                'perPerson.age': 56,
                'empJob.department': 'Research & Development',
                'empJob.jobTitle': 'Research Scientist',
                'empJob.payGrade': 1,
                'timeManagement.overtimeFlag': 0,
                'empPayCompRecurring.monthlyIncome': 2066,
                'empEmployment.yearsAtCompany': 3},
  'riskScores': {'burnout': 0.012, 'mentalHealth': 0.17, 'attrition': 0.029},
  'cbri': 0.062,
  'riskLevel': 'Low',
  'topFactors': [{'factor': 'high workload / resource demand', 'direction': 'decreases'},
                 {'factor': 'workload relative to seniority', 'direction': 'decreases'},
                 {'factor': 'seniority level', 'direction': 'decreases'}],
  'explanationNarrative': 'Low burnout risk (1%). The risk is driven primarily by high workload / resource demand. No '
                          'action indicated; continue routine support.',
  'recommendedAction': 'No action indicated; continue routine support.'},
 {'employeeId': 'E10013',
  'department': 'Sales',
  'jobTitle': 'Sales Executive',
  'sapFields': {'perPersonal.gender': 'Male',
                'perPerson.age': 38,
                'empJob.department': 'Sales',
                'empJob.jobTitle': 'Sales Executive',
                'empJob.payGrade': 3,
                'timeManagement.overtimeFlag': 0,
                'empPayCompRecurring.monthlyIncome': 10609,
                'empEmployment.yearsAtCompany': 16},
  'riskScores': {'burnout': 0.031, 'mentalHealth': 0.097, 'attrition': 0.022},
  'cbri': 0.049,
  'riskLevel': 'Low',
  'topFactors': [{'factor': 'high workload / resource demand', 'direction': 'decreases'},
                 {'factor': 'workload relative to seniority', 'direction': 'decreases'},
                 {'factor': 'no work-from-home option', 'direction': 'decreases'}],
  'explanationNarrative': 'Low burnout risk (3%). The risk is driven primarily by high workload / resource demand. No '
                          'action indicated; continue routine support.',
  'recommendedAction': 'No action indicated; continue routine support.'},
 {'employeeId': 'E10014',
  'department': 'Research & Development',
  'jobTitle': 'Manufacturing Director',
  'sapFields': {'perPersonal.gender': 'Male',
                'perPerson.age': 59,
                'empJob.department': 'Research & Development',
                'empJob.jobTitle': 'Manufacturing Director',
                'empJob.payGrade': 3,
                'timeManagement.overtimeFlag': 0,
                'empPayCompRecurring.monthlyIncome': 10512,
                'empEmployment.yearsAtCompany': 9},
  'riskScores': {'burnout': 0.037, 'mentalHealth': 0.062, 'attrition': 0.025},
  'cbri': 0.042,
  'riskLevel': 'Low',
  'topFactors': [{'factor': 'high workload / resource demand', 'direction': 'decreases'},
                 {'factor': 'workload relative to seniority', 'direction': 'decreases'},
                 {'factor': 'no work-from-home option', 'direction': 'increases'}],
  'explanationNarrative': 'Low burnout risk (4%). The risk is driven primarily by no work-from-home option. No action '
                          'indicated; continue routine support.',
  'recommendedAction': 'No action indicated; continue routine support.'},
 {'employeeId': 'E10015',
  'department': 'Sales',
  'jobTitle': 'Sales Executive',
  'sapFields': {'perPersonal.gender': 'Female',
                'perPerson.age': 56,
                'empJob.department': 'Sales',
                'empJob.jobTitle': 'Sales Executive',
                'empJob.payGrade': 2,
                'timeManagement.overtimeFlag': 0,
                'empPayCompRecurring.monthlyIncome': 5380,
                'empEmployment.yearsAtCompany': 0},
  'riskScores': {'burnout': 0.054, 'mentalHealth': 0.199, 'attrition': 0.033},
  'cbri': 0.093,
  'riskLevel': 'Low',
  'topFactors': [{'factor': 'high workload / resource demand', 'direction': 'decreases'},
                 {'factor': 'workload relative to seniority', 'direction': 'decreases'},
                 {'factor': 'no work-from-home option', 'direction': 'increases'}],
  'explanationNarrative': 'Low burnout risk (5%). The risk is driven primarily by no work-from-home option. No action '
                          'indicated; continue routine support.',
  'recommendedAction': 'No action indicated; continue routine support.'},
 {'employeeId': 'E10016',
  'department': 'Research & Development',
  'jobTitle': 'Research Scientist',
  'sapFields': {'perPersonal.gender': 'Male',
                'perPerson.age': 32,
                'empJob.department': 'Research & Development',
                'empJob.jobTitle': 'Research Scientist',
                'empJob.payGrade': 1,
                'timeManagement.overtimeFlag': 1,
                'empPayCompRecurring.monthlyIncome': 3298,
                'empEmployment.yearsAtCompany': 6},
  'riskScores': {'burnout': 0.12, 'mentalHealth': 0.15, 'attrition': 0.034},
  'cbri': 0.112,
  'riskLevel': 'Low',
  'topFactors': [{'factor': 'no work-from-home option', 'direction': 'decreases'},
                 {'factor': 'work-from-home available', 'direction': 'decreases'},
                 {'factor': 'gender (male)', 'direction': 'decreases'}],
  'explanationNarrative': 'Low burnout risk (12%). The risk is driven primarily by no work-from-home option. No action '
                          'indicated; continue routine support.',
  'recommendedAction': 'No action indicated; continue routine support.'},
 {'employeeId': 'E10017',
  'department': 'Sales',
  'jobTitle': 'Sales Executive',
  'sapFields': {'perPersonal.gender': 'Female',
                'perPerson.age': 54,
                'empJob.department': 'Sales',
                'empJob.jobTitle': 'Sales Executive',
                'empJob.payGrade': 3,
                'timeManagement.overtimeFlag': 0,
                'empPayCompRecurring.monthlyIncome': 10686,
                'empEmployment.yearsAtCompany': 9},
  'riskScores': {'burnout': 0.103, 'mentalHealth': 0.229, 'attrition': 0.044},
  'cbri': 0.129,
  'riskLevel': 'Low',
  'topFactors': [{'factor': 'high workload / resource demand', 'direction': 'decreases'},
                 {'factor': 'seniority level', 'direction': 'decreases'},
                 {'factor': 'work-from-home available', 'direction': 'increases'}],
  'explanationNarrative': 'Low burnout risk (10%). The risk is driven primarily by work-from-home available. No action '
                          'indicated; continue routine support.',
  'recommendedAction': 'No action indicated; continue routine support.'},
 {'employeeId': 'E10018',
  'department': 'Human Resources',
  'jobTitle': 'Human Resources',
  'sapFields': {'perPersonal.gender': 'Male',
                'perPerson.age': 43,
                'empJob.department': 'Human Resources',
                'empJob.jobTitle': 'Human Resources',
                'empJob.payGrade': 1,
                'timeManagement.overtimeFlag': 0,
                'empPayCompRecurring.monthlyIncome': 3539,
                'empEmployment.yearsAtCompany': 9},
  'riskScores': {'burnout': 0.129, 'mentalHealth': 0.269, 'attrition': 0.042},
  'cbri': 0.154,
  'riskLevel': 'Low',
  'topFactors': [{'factor': 'work-from-home available', 'direction': 'decreases'},
                 {'factor': 'workload relative to seniority', 'direction': 'decreases'},
                 {'factor': 'no work-from-home option', 'direction': 'decreases'}],
  'explanationNarrative': 'Low burnout risk (13%). The risk is driven primarily by work-from-home available. No action '
                          'indicated; continue routine support.',
  'recommendedAction': 'No action indicated; continue routine support.'},
 {'employeeId': 'E10019',
  'department': 'Research & Development',
  'jobTitle': 'Research Director',
  'sapFields': {'perPersonal.gender': 'Male',
                'perPerson.age': 37,
                'empJob.department': 'Research & Development',
                'empJob.jobTitle': 'Research Director',
                'empJob.payGrade': 3,
                'timeManagement.overtimeFlag': 1,
                'empPayCompRecurring.monthlyIncome': 12185,
                'empEmployment.yearsAtCompany': 10},
  'riskScores': {'burnout': 0.098, 'mentalHealth': 0.308, 'attrition': 0.042},
  'cbri': 0.15,
  'riskLevel': 'Low',
  'topFactors': [{'factor': 'high workload / resource demand', 'direction': 'decreases'},
                 {'factor': 'seniority level', 'direction': 'decreases'},
                 {'factor': 'no work-from-home option', 'direction': 'increases'}],
  'explanationNarrative': 'Low burnout risk (10%). The risk is driven primarily by no work-from-home option. No action '
                          'indicated; continue routine support.',
  'recommendedAction': 'No action indicated; continue routine support.'},
 {'employeeId': 'E10020',
  'department': 'Research & Development',
  'jobTitle': 'Healthcare Representative',
  'sapFields': {'perPersonal.gender': 'Female',
                'perPerson.age': 37,
                'empJob.department': 'Research & Development',
                'empJob.jobTitle': 'Healthcare Representative',
                'empJob.payGrade': 2,
                'timeManagement.overtimeFlag': 0,
                'empPayCompRecurring.monthlyIncome': 4107,
                'empEmployment.yearsAtCompany': 4},
  'riskScores': {'burnout': 0.214, 'mentalHealth': 0.721, 'attrition': 0.066},
  'cbri': 0.337,
  'riskLevel': 'Low',
  'topFactors': [{'factor': 'high workload / resource demand', 'direction': 'decreases'},
                 {'factor': 'workload relative to seniority', 'direction': 'increases'},
                 {'factor': 'seniority level', 'direction': 'decreases'}],
  'explanationNarrative': 'Low burnout risk (21%). The risk is driven primarily by workload relative to seniority. No '
                          'action indicated; continue routine support.',
  'recommendedAction': 'No action indicated; continue routine support.'},
 {'employeeId': 'E10021',
  'department': 'Sales',
  'jobTitle': 'Sales Executive',
  'sapFields': {'perPersonal.gender': 'Female',
                'perPerson.age': 37,
                'empJob.department': 'Sales',
                'empJob.jobTitle': 'Sales Executive',
                'empJob.payGrade': 2,
                'timeManagement.overtimeFlag': 1,
                'empPayCompRecurring.monthlyIncome': 6694,
                'empEmployment.yearsAtCompany': 1},
  'riskScores': {'burnout': 0.136, 'mentalHealth': 0.409, 'attrition': 0.059},
  'cbri': 0.203,
  'riskLevel': 'Low',
  'topFactors': [{'factor': 'no work-from-home option', 'direction': 'decreases'},
                 {'factor': 'work-from-home available', 'direction': 'decreases'},
                 {'factor': 'gender (male)', 'direction': 'decreases'}],
  'explanationNarrative': 'Low burnout risk (14%). The risk is driven primarily by no work-from-home option. No action '
                          'indicated; continue routine support.',
  'recommendedAction': 'No action indicated; continue routine support.'},
 {'employeeId': 'E10022',
  'department': 'Sales',
  'jobTitle': 'Manager',
  'sapFields': {'perPersonal.gender': 'Female',
                'perPerson.age': 46,
                'empJob.department': 'Sales',
                'empJob.jobTitle': 'Manager',
                'empJob.payGrade': 4,
                'timeManagement.overtimeFlag': 0,
                'empPayCompRecurring.monthlyIncome': 16606,
                'empEmployment.yearsAtCompany': 13},
  'riskScores': {'burnout': 0.176, 'mentalHealth': 0.341, 'attrition': 0.066},
  'cbri': 0.203,
  'riskLevel': 'Low',
  'topFactors': [{'factor': 'no work-from-home option', 'direction': 'decreases'},
                 {'factor': 'work-from-home available', 'direction': 'decreases'},
                 {'factor': 'workload relative to seniority', 'direction': 'decreases'}],
  'explanationNarrative': 'Low burnout risk (18%). The risk is driven primarily by no work-from-home option. No action '
                          'indicated; continue routine support.',
  'recommendedAction': 'No action indicated; continue routine support.'},
 {'employeeId': 'E10023',
  'department': 'Research & Development',
  'jobTitle': 'Research Scientist',
  'sapFields': {'perPersonal.gender': 'Male',
                'perPerson.age': 32,
                'empJob.department': 'Research & Development',
                'empJob.jobTitle': 'Research Scientist',
                'empJob.payGrade': 1,
                'timeManagement.overtimeFlag': 0,
                'empPayCompRecurring.monthlyIncome': 2439,
                'empEmployment.yearsAtCompany': 4},
  'riskScores': {'burnout': 0.177, 'mentalHealth': 0.479, 'attrition': 0.06},
  'cbri': 0.244,
  'riskLevel': 'Low',
  'topFactors': [{'factor': 'no work-from-home option', 'direction': 'decreases'},
                 {'factor': 'work-from-home available', 'direction': 'decreases'},
                 {'factor': 'workload relative to seniority', 'direction': 'decreases'}],
  'explanationNarrative': 'Low burnout risk (18%). The risk is driven primarily by no work-from-home option. No action '
                          'indicated; continue routine support.',
  'recommendedAction': 'No action indicated; continue routine support.'},
 {'employeeId': 'E10024',
  'department': 'Sales',
  'jobTitle': 'Sales Executive',
  'sapFields': {'perPersonal.gender': 'Male',
                'perPerson.age': 36,
                'empJob.department': 'Sales',
                'empJob.jobTitle': 'Sales Executive',
                'empJob.payGrade': 2,
                'timeManagement.overtimeFlag': 1,
                'empPayCompRecurring.monthlyIncome': 6201,
                'empEmployment.yearsAtCompany': 18},
  'riskScores': {'burnout': 0.237, 'mentalHealth': 0.577, 'attrition': 0.068},
  'cbri': 0.305,
  'riskLevel': 'Low',
  'topFactors': [{'factor': 'workload relative to seniority', 'direction': 'decreases'},
                 {'factor': 'no work-from-home option', 'direction': 'decreases'},
                 {'factor': 'work-from-home available', 'direction': 'decreases'}],
  'explanationNarrative': 'Low burnout risk (24%). The risk is driven primarily by workload relative to seniority. No '
                          'action indicated; continue routine support.',
  'recommendedAction': 'No action indicated; continue routine support.'},
 {'employeeId': 'E10025',
  'department': 'Research & Development',
  'jobTitle': 'Healthcare Representative',
  'sapFields': {'perPersonal.gender': 'Female',
                'perPerson.age': 46,
                'empJob.department': 'Research & Development',
                'empJob.jobTitle': 'Healthcare Representative',
                'empJob.payGrade': 3,
                'timeManagement.overtimeFlag': 0,
                'empPayCompRecurring.monthlyIncome': 10527,
                'empEmployment.yearsAtCompany': 2},
  'riskScores': {'burnout': 0.196, 'mentalHealth': 0.687, 'attrition': 0.076},
  'cbri': 0.319,
  'riskLevel': 'Low',
  'topFactors': [{'factor': 'workload relative to seniority', 'direction': 'decreases'},
                 {'factor': 'no work-from-home option', 'direction': 'decreases'},
                 {'factor': 'work-from-home available', 'direction': 'decreases'}],
  'explanationNarrative': 'Low burnout risk (20%). The risk is driven primarily by workload relative to seniority. No '
                          'action indicated; continue routine support.',
  'recommendedAction': 'No action indicated; continue routine support.'},
 {'employeeId': 'E10026',
  'department': 'Research & Development',
  'jobTitle': 'Research Scientist',
  'sapFields': {'perPersonal.gender': 'Female',
                'perPerson.age': 56,
                'empJob.department': 'Research & Development',
                'empJob.jobTitle': 'Research Scientist',
                'empJob.payGrade': 1,
                'timeManagement.overtimeFlag': 0,
                'empPayCompRecurring.monthlyIncome': 2942,
                'empEmployment.yearsAtCompany': 5},
  'riskScores': {'burnout': 0.246, 'mentalHealth': 0.573, 'attrition': 0.072},
  'cbri': 0.309,
  'riskLevel': 'Low',
  'topFactors': [{'factor': 'workload relative to seniority', 'direction': 'decreases'},
                 {'factor': 'no work-from-home option', 'direction': 'decreases'},
                 {'factor': 'high workload / resource demand', 'direction': 'increases'}],
  'explanationNarrative': 'Low burnout risk (25%). The risk is driven primarily by high workload / resource demand. No '
                          'action indicated; continue routine support.',
  'recommendedAction': 'No action indicated; continue routine support.'},
 {'employeeId': 'E10027',
  'department': 'Sales',
  'jobTitle': 'Sales Executive',
  'sapFields': {'perPersonal.gender': 'Male',
                'perPerson.age': 49,
                'empJob.department': 'Sales',
                'empJob.jobTitle': 'Sales Executive',
                'empJob.payGrade': 4,
                'timeManagement.overtimeFlag': 0,
                'empPayCompRecurring.monthlyIncome': 13120,
                'empEmployment.yearsAtCompany': 9},
  'riskScores': {'burnout': 0.364, 'mentalHealth': 0.903, 'attrition': 0.09},
  'cbri': 0.471,
  'riskLevel': 'Medium',
  'topFactors': [{'factor': 'no work-from-home option', 'direction': 'increases'},
                 {'factor': 'work-from-home available', 'direction': 'increases'},
                 {'factor': 'gender (male)', 'direction': 'decreases'}],
  'explanationNarrative': 'Low burnout risk (36%). The risk is driven primarily by no work-from-home option and '
                          'work-from-home available. No action indicated; continue routine support.',
  'recommendedAction': 'No action indicated; continue routine support.'},
 {'employeeId': 'E10028',
  'department': 'Research & Development',
  'jobTitle': 'Laboratory Technician',
  'sapFields': {'perPersonal.gender': 'Male',
                'perPerson.age': 35,
                'empJob.department': 'Research & Development',
                'empJob.jobTitle': 'Laboratory Technician',
                'empJob.payGrade': 2,
                'timeManagement.overtimeFlag': 0,
                'empPayCompRecurring.monthlyIncome': 3681,
                'empEmployment.yearsAtCompany': 3},
  'riskScores': {'burnout': 0.516, 'mentalHealth': 0.878, 'attrition': 0.088},
  'cbri': 0.539,
  'riskLevel': 'Medium',
  'topFactors': [{'factor': 'workload relative to seniority', 'direction': 'increases'},
                 {'factor': 'no work-from-home option', 'direction': 'decreases'},
                 {'factor': 'work-from-home available', 'direction': 'decreases'}],
  'explanationNarrative': 'Medium burnout risk (52%). The risk is driven primarily by workload relative to seniority. '
                          'Suggested: monitor and offer a voluntary wellbeing conversation.',
  'recommendedAction': 'Suggested: monitor and offer a voluntary wellbeing conversation.'},
 {'employeeId': 'E10029',
  'department': 'Research & Development',
  'jobTitle': 'Laboratory Technician',
  'sapFields': {'perPersonal.gender': 'Male',
                'perPerson.age': 25,
                'empJob.department': 'Research & Development',
                'empJob.jobTitle': 'Laboratory Technician',
                'empJob.payGrade': 1,
                'timeManagement.overtimeFlag': 0,
                'empPayCompRecurring.monthlyIncome': 3669,
                'empEmployment.yearsAtCompany': 3},
  'riskScores': {'burnout': 0.439, 'mentalHealth': 0.903, 'attrition': 0.095},
  'cbri': 0.51,
  'riskLevel': 'Medium',
  'topFactors': [{'factor': 'workload relative to seniority', 'direction': 'decreases'},
                 {'factor': 'no work-from-home option', 'direction': 'increases'},
                 {'factor': 'work-from-home available', 'direction': 'increases'}],
  'explanationNarrative': 'Medium burnout risk (44%). The risk is driven primarily by no work-from-home option and '
                          'work-from-home available. Suggested: monitor and offer a voluntary wellbeing conversation.',
  'recommendedAction': 'Suggested: monitor and offer a voluntary wellbeing conversation.'},
 {'employeeId': 'E10030',
  'department': 'Research & Development',
  'jobTitle': 'Manufacturing Director',
  'sapFields': {'perPersonal.gender': 'Male',
                'perPerson.age': 28,
                'empJob.department': 'Research & Development',
                'empJob.jobTitle': 'Manufacturing Director',
                'empJob.payGrade': 2,
                'timeManagement.overtimeFlag': 0,
                'empPayCompRecurring.monthlyIncome': 6549,
                'empEmployment.yearsAtCompany': 8},
  'riskScores': {'burnout': 0.303, 'mentalHealth': 0.916, 'attrition': 0.1},
  'cbri': 0.446,
  'riskLevel': 'Medium',
  'topFactors': [{'factor': 'workload relative to seniority', 'direction': 'increases'},
                 {'factor': 'no work-from-home option', 'direction': 'decreases'},
                 {'factor': 'work-from-home available', 'direction': 'decreases'}],
  'explanationNarrative': 'Low burnout risk (30%). The risk is driven primarily by workload relative to seniority. No '
                          'action indicated; continue routine support.',
  'recommendedAction': 'No action indicated; continue routine support.'},
 {'employeeId': 'E10031',
  'department': 'Research & Development',
  'jobTitle': 'Laboratory Technician',
  'sapFields': {'perPersonal.gender': 'Male',
                'perPerson.age': 44,
                'empJob.department': 'Research & Development',
                'empJob.jobTitle': 'Laboratory Technician',
                'empJob.payGrade': 1,
                'timeManagement.overtimeFlag': 0,
                'empPayCompRecurring.monthlyIncome': 3708,
                'empEmployment.yearsAtCompany': 5},
  'riskScores': {'burnout': 0.689, 'mentalHealth': 0.979, 'attrition': 0.15},
  'cbri': 0.668,
  'riskLevel': 'High',
  'topFactors': [{'factor': 'workload relative to seniority', 'direction': 'decreases'},
                 {'factor': 'no work-from-home option', 'direction': 'increases'},
                 {'factor': 'work-from-home available', 'direction': 'increases'}],
  'explanationNarrative': 'Medium burnout risk (69%). The risk is driven primarily by no work-from-home option and '
                          'work-from-home available. Suggested: monitor and offer a voluntary wellbeing conversation.',
  'recommendedAction': 'Suggested: monitor and offer a voluntary wellbeing conversation.'},
 {'employeeId': 'E10032',
  'department': 'Sales',
  'jobTitle': 'Sales Representative',
  'sapFields': {'perPersonal.gender': 'Female',
                'perPerson.age': 32,
                'empJob.department': 'Sales',
                'empJob.jobTitle': 'Sales Representative',
                'empJob.payGrade': 1,
                'timeManagement.overtimeFlag': 0,
                'empPayCompRecurring.monthlyIncome': 2827,
                'empEmployment.yearsAtCompany': 1},
  'riskScores': {'burnout': 0.536, 'mentalHealth': 0.95, 'attrition': 0.13},
  'cbri': 0.579,
  'riskLevel': 'Medium',
  'topFactors': [{'factor': 'no work-from-home option', 'direction': 'increases'},
                 {'factor': 'work-from-home available', 'direction': 'increases'},
                 {'factor': 'high workload / resource demand', 'direction': 'decreases'}],
  'explanationNarrative': 'Medium burnout risk (54%). The risk is driven primarily by no work-from-home option and '
                          'work-from-home available. Suggested: monitor and offer a voluntary wellbeing conversation.',
  'recommendedAction': 'Suggested: monitor and offer a voluntary wellbeing conversation.'},
 {'employeeId': 'E10033',
  'department': 'Research & Development',
  'jobTitle': 'Manufacturing Director',
  'sapFields': {'perPersonal.gender': 'Male',
                'perPerson.age': 31,
                'empJob.department': 'Research & Development',
                'empJob.jobTitle': 'Manufacturing Director',
                'empJob.payGrade': 2,
                'timeManagement.overtimeFlag': 1,
                'empPayCompRecurring.monthlyIncome': 6179,
                'empEmployment.yearsAtCompany': 10},
  'riskScores': {'burnout': 0.522, 'mentalHealth': 0.914, 'attrition': 0.121},
  'cbri': 0.559,
  'riskLevel': 'Medium',
  'topFactors': [{'factor': 'no work-from-home option', 'direction': 'increases'},
                 {'factor': 'work-from-home available', 'direction': 'increases'},
                 {'factor': 'high workload / resource demand', 'direction': 'decreases'}],
  'explanationNarrative': 'Medium burnout risk (52%). The risk is driven primarily by no work-from-home option and '
                          'work-from-home available. Suggested: monitor and offer a voluntary wellbeing conversation.',
  'recommendedAction': 'Suggested: monitor and offer a voluntary wellbeing conversation.'},
 {'employeeId': 'E10034',
  'department': 'Sales',
  'jobTitle': 'Sales Executive',
  'sapFields': {'perPersonal.gender': 'Female',
                'perPerson.age': 39,
                'empJob.department': 'Sales',
                'empJob.jobTitle': 'Sales Executive',
                'empJob.payGrade': 2,
                'timeManagement.overtimeFlag': 0,
                'empPayCompRecurring.monthlyIncome': 5736,
                'empEmployment.yearsAtCompany': 3},
  'riskScores': {'burnout': 0.834, 'mentalHealth': 0.971, 'attrition': 0.175},
  'cbri': 0.743,
  'riskLevel': 'High',
  'topFactors': [{'factor': 'workload relative to seniority', 'direction': 'increases'},
                 {'factor': 'work-from-home available', 'direction': 'increases'},
                 {'factor': 'no work-from-home option', 'direction': 'increases'}],
  'explanationNarrative': 'High burnout risk (83%). The risk is driven primarily by workload relative to seniority and '
                          'work-from-home available. Recommended: a confidential wellbeing check-in and a workload '
                          'review this cycle.',
  'recommendedAction': 'Recommended: a confidential wellbeing check-in and a workload review this cycle.'},
 {'employeeId': 'E10035',
  'department': 'Research & Development',
  'jobTitle': 'Manufacturing Director',
  'sapFields': {'perPersonal.gender': 'Female',
                'perPerson.age': 30,
                'empJob.department': 'Research & Development',
                'empJob.jobTitle': 'Manufacturing Director',
                'empJob.payGrade': 3,
                'timeManagement.overtimeFlag': 0,
                'empPayCompRecurring.monthlyIncome': 9667,
                'empEmployment.yearsAtCompany': 7},
  'riskScores': {'burnout': 0.706, 'mentalHealth': 0.937, 'attrition': 0.139},
  'cbri': 0.662,
  'riskLevel': 'High',
  'topFactors': [{'factor': 'high workload / resource demand', 'direction': 'increases'},
                 {'factor': 'workload relative to seniority', 'direction': 'decreases'},
                 {'factor': 'work-from-home available', 'direction': 'decreases'}],
  'explanationNarrative': 'High burnout risk (71%). The risk is driven primarily by high workload / resource demand. '
                          'Recommended: a confidential wellbeing check-in and a workload review this cycle.',
  'recommendedAction': 'Recommended: a confidential wellbeing check-in and a workload review this cycle.'},
 {'employeeId': 'E10036',
  'department': 'Research & Development',
  'jobTitle': 'Research Scientist',
  'sapFields': {'perPersonal.gender': 'Male',
                'perPerson.age': 51,
                'empJob.department': 'Research & Development',
                'empJob.jobTitle': 'Research Scientist',
                'empJob.payGrade': 1,
                'timeManagement.overtimeFlag': 1,
                'empPayCompRecurring.monthlyIncome': 2461,
                'empEmployment.yearsAtCompany': 10},
  'riskScores': {'burnout': 0.921, 'mentalHealth': 0.955, 'attrition': 0.193},
  'cbri': 0.786,
  'riskLevel': 'High',
  'topFactors': [{'factor': 'high workload / resource demand', 'direction': 'increases'},
                 {'factor': 'work-from-home available', 'direction': 'increases'},
                 {'factor': 'no work-from-home option', 'direction': 'increases'}],
  'explanationNarrative': 'High burnout risk (92%). The risk is driven primarily by high workload / resource demand '
                          'and work-from-home available. Recommended: a confidential wellbeing check-in and a workload '
                          'review this cycle.',
  'recommendedAction': 'Recommended: a confidential wellbeing check-in and a workload review this cycle.'},
 {'employeeId': 'E10037',
  'department': 'Research & Development',
  'jobTitle': 'Research Scientist',
  'sapFields': {'perPersonal.gender': 'Female',
                'perPerson.age': 21,
                'empJob.department': 'Research & Development',
                'empJob.jobTitle': 'Research Scientist',
                'empJob.payGrade': 1,
                'timeManagement.overtimeFlag': 0,
                'empPayCompRecurring.monthlyIncome': 2693,
                'empEmployment.yearsAtCompany': 1},
  'riskScores': {'burnout': 0.72, 'mentalHealth': 0.977, 'attrition': 0.149},
  'cbri': 0.683,
  'riskLevel': 'High',
  'topFactors': [{'factor': 'high workload / resource demand', 'direction': 'increases'},
                 {'factor': 'workload relative to seniority', 'direction': 'decreases'},
                 {'factor': 'no work-from-home option', 'direction': 'decreases'}],
  'explanationNarrative': 'High burnout risk (72%). The risk is driven primarily by high workload / resource demand. '
                          'Recommended: a confidential wellbeing check-in and a workload review this cycle.',
  'recommendedAction': 'Recommended: a confidential wellbeing check-in and a workload review this cycle.'},
 {'employeeId': 'E10038',
  'department': 'Sales',
  'jobTitle': 'Sales Executive',
  'sapFields': {'perPersonal.gender': 'Female',
                'perPerson.age': 33,
                'empJob.department': 'Sales',
                'empJob.jobTitle': 'Sales Executive',
                'empJob.payGrade': 2,
                'timeManagement.overtimeFlag': 0,
                'empPayCompRecurring.monthlyIncome': 5147,
                'empEmployment.yearsAtCompany': 11},
  'riskScores': {'burnout': 0.674, 'mentalHealth': 0.961, 'attrition': 0.179},
  'cbri': 0.661,
  'riskLevel': 'High',
  'topFactors': [{'factor': 'workload relative to seniority', 'direction': 'decreases'},
                 {'factor': 'no work-from-home option', 'direction': 'increases'},
                 {'factor': 'work-from-home available', 'direction': 'increases'}],
  'explanationNarrative': 'Medium burnout risk (67%). The risk is driven primarily by no work-from-home option and '
                          'work-from-home available. Suggested: monitor and offer a voluntary wellbeing conversation.',
  'recommendedAction': 'Suggested: monitor and offer a voluntary wellbeing conversation.'},
 {'employeeId': 'E10039',
  'department': 'Research & Development',
  'jobTitle': 'Healthcare Representative',
  'sapFields': {'perPersonal.gender': 'Male',
                'perPerson.age': 29,
                'empJob.department': 'Research & Development',
                'empJob.jobTitle': 'Healthcare Representative',
                'empJob.payGrade': 2,
                'timeManagement.overtimeFlag': 1,
                'empPayCompRecurring.monthlyIncome': 6294,
                'empEmployment.yearsAtCompany': 3},
  'riskScores': {'burnout': 0.927, 'mentalHealth': 0.977, 'attrition': 0.247},
  'cbri': 0.806,
  'riskLevel': 'High',
  'topFactors': [{'factor': 'seniority level', 'direction': 'increases'},
                 {'factor': 'high workload / resource demand', 'direction': 'increases'},
                 {'factor': 'workload relative to seniority', 'direction': 'decreases'}],
  'explanationNarrative': 'High burnout risk (93%). The risk is driven primarily by seniority level and high workload '
                          '/ resource demand. Recommended: a confidential wellbeing check-in and a workload review '
                          'this cycle.',
  'recommendedAction': 'Recommended: a confidential wellbeing check-in and a workload review this cycle.'},
 {'employeeId': 'E10040',
  'department': 'Research & Development',
  'jobTitle': 'Manufacturing Director',
  'sapFields': {'perPersonal.gender': 'Female',
                'perPerson.age': 40,
                'empJob.department': 'Research & Development',
                'empJob.jobTitle': 'Manufacturing Director',
                'empJob.payGrade': 3,
                'timeManagement.overtimeFlag': 1,
                'empPayCompRecurring.monthlyIncome': 7945,
                'empEmployment.yearsAtCompany': 4},
  'riskScores': {'burnout': 0.839, 'mentalHealth': 0.984, 'attrition': 0.326},
  'cbri': 0.78,
  'riskLevel': 'High',
  'topFactors': [{'factor': 'high workload / resource demand', 'direction': 'increases'},
                 {'factor': 'workload relative to seniority', 'direction': 'decreases'},
                 {'factor': 'work-from-home available', 'direction': 'increases'}],
  'explanationNarrative': 'High burnout risk (84%). The risk is driven primarily by high workload / resource demand '
                          'and work-from-home available. Recommended: a confidential wellbeing check-in and a workload '
                          'review this cycle.',
  'recommendedAction': 'Recommended: a confidential wellbeing check-in and a workload review this cycle.'},
 {'employeeId': 'E10041',
  'department': 'Research & Development',
  'jobTitle': 'Manufacturing Director',
  'sapFields': {'perPersonal.gender': 'Female',
                'perPerson.age': 40,
                'empJob.department': 'Research & Development',
                'empJob.jobTitle': 'Manufacturing Director',
                'empJob.payGrade': 3,
                'timeManagement.overtimeFlag': 1,
                'empPayCompRecurring.monthlyIncome': 7945,
                'empEmployment.yearsAtCompany': 4},
  'riskScores': {'burnout': 0.912, 'mentalHealth': 0.986, 'attrition': 0.326},
  'cbri': 0.817,
  'riskLevel': 'High',
  'topFactors': [{'factor': 'high workload / resource demand', 'direction': 'increases'},
                 {'factor': 'work-from-home available', 'direction': 'increases'},
                 {'factor': 'no work-from-home option', 'direction': 'increases'}],
  'explanationNarrative': 'High burnout risk (91%). The risk is driven primarily by high workload / resource demand '
                          'and work-from-home available. Recommended: a confidential wellbeing check-in and a workload '
                          'review this cycle.',
  'recommendedAction': 'Recommended: a confidential wellbeing check-in and a workload review this cycle.'},
 {'employeeId': 'E10042',
  'department': 'Research & Development',
  'jobTitle': 'Research Scientist',
  'sapFields': {'perPersonal.gender': 'Male',
                'perPerson.age': 35,
                'empJob.department': 'Research & Development',
                'empJob.jobTitle': 'Research Scientist',
                'empJob.payGrade': 2,
                'timeManagement.overtimeFlag': 1,
                'empPayCompRecurring.monthlyIncome': 4249,
                'empEmployment.yearsAtCompany': 9},
  'riskScores': {'burnout': 0.93, 'mentalHealth': 0.991, 'attrition': 0.334},
  'cbri': 0.829,
  'riskLevel': 'High',
  'topFactors': [{'factor': 'high workload / resource demand', 'direction': 'increases'},
                 {'factor': 'work-from-home available', 'direction': 'increases'},
                 {'factor': 'no work-from-home option', 'direction': 'increases'}],
  'explanationNarrative': 'High burnout risk (93%). The risk is driven primarily by high workload / resource demand '
                          'and work-from-home available. Recommended: a confidential wellbeing check-in and a workload '
                          'review this cycle.',
  'recommendedAction': 'Recommended: a confidential wellbeing check-in and a workload review this cycle.'},
 {'employeeId': 'E10043',
  'department': 'Research & Development',
  'jobTitle': 'Laboratory Technician',
  'sapFields': {'perPersonal.gender': 'Male',
                'perPerson.age': 24,
                'empJob.department': 'Research & Development',
                'empJob.jobTitle': 'Laboratory Technician',
                'empJob.payGrade': 1,
                'timeManagement.overtimeFlag': 0,
                'empPayCompRecurring.monthlyIncome': 3597,
                'empEmployment.yearsAtCompany': 4},
  'riskScores': {'burnout': 0.98, 'mentalHealth': 0.986, 'attrition': 0.355},
  'cbri': 0.857,
  'riskLevel': 'High',
  'topFactors': [{'factor': 'seniority level', 'direction': 'increases'},
                 {'factor': 'high workload / resource demand', 'direction': 'increases'},
                 {'factor': 'workload relative to seniority', 'direction': 'decreases'}],
  'explanationNarrative': 'High burnout risk (98%). The risk is driven primarily by seniority level and high workload '
                          '/ resource demand. Recommended: a confidential wellbeing check-in and a workload review '
                          'this cycle.',
  'recommendedAction': 'Recommended: a confidential wellbeing check-in and a workload review this cycle.'},
 {'employeeId': 'E10044',
  'department': 'Human Resources',
  'jobTitle': 'Human Resources',
  'sapFields': {'perPersonal.gender': 'Female',
                'perPerson.age': 26,
                'empJob.department': 'Human Resources',
                'empJob.jobTitle': 'Human Resources',
                'empJob.payGrade': 1,
                'timeManagement.overtimeFlag': 1,
                'empPayCompRecurring.monthlyIncome': 2148,
                'empEmployment.yearsAtCompany': 5},
  'riskScores': {'burnout': 0.996, 'mentalHealth': 0.979, 'attrition': 0.327},
  'cbri': 0.857,
  'riskLevel': 'High',
  'topFactors': [{'factor': 'high workload / resource demand', 'direction': 'increases'},
                 {'factor': 'seniority level', 'direction': 'increases'},
                 {'factor': 'workload relative to seniority', 'direction': 'decreases'}],
  'explanationNarrative': 'High burnout risk (100%). The risk is driven primarily by high workload / resource demand '
                          'and seniority level. Recommended: a confidential wellbeing check-in and a workload review '
                          'this cycle.',
  'recommendedAction': 'Recommended: a confidential wellbeing check-in and a workload review this cycle.'},
 {'employeeId': 'E10045',
  'department': 'Research & Development',
  'jobTitle': 'Laboratory Technician',
  'sapFields': {'perPersonal.gender': 'Female',
                'perPerson.age': 30,
                'empJob.department': 'Research & Development',
                'empJob.jobTitle': 'Laboratory Technician',
                'empJob.payGrade': 1,
                'timeManagement.overtimeFlag': 0,
                'empPayCompRecurring.monthlyIncome': 2422,
                'empEmployment.yearsAtCompany': 3},
  'riskScores': {'burnout': 0.997, 'mentalHealth': 0.994, 'attrition': 0.388},
  'cbri': 0.874,
  'riskLevel': 'High',
  'topFactors': [{'factor': 'high workload / resource demand', 'direction': 'increases'},
                 {'factor': 'seniority level', 'direction': 'increases'},
                 {'factor': 'work-from-home available', 'direction': 'increases'}],
  'explanationNarrative': 'High burnout risk (100%). The risk is driven primarily by high workload / resource demand '
                          'and seniority level. Recommended: a confidential wellbeing check-in and a workload review '
                          'this cycle.',
  'recommendedAction': 'Recommended: a confidential wellbeing check-in and a workload review this cycle.'},
 {'employeeId': 'E10046',
  'department': 'Research & Development',
  'jobTitle': 'Research Scientist',
  'sapFields': {'perPersonal.gender': 'Male',
                'perPerson.age': 42,
                'empJob.department': 'Research & Development',
                'empJob.jobTitle': 'Research Scientist',
                'empJob.payGrade': 1,
                'timeManagement.overtimeFlag': 1,
                'empPayCompRecurring.monthlyIncome': 2759,
                'empEmployment.yearsAtCompany': 2},
  'riskScores': {'burnout': 0.992, 'mentalHealth': 0.993, 'attrition': 0.43},
  'cbri': 0.88,
  'riskLevel': 'High',
  'topFactors': [{'factor': 'high workload / resource demand', 'direction': 'increases'},
                 {'factor': 'seniority level', 'direction': 'increases'},
                 {'factor': 'workload relative to seniority', 'direction': 'decreases'}],
  'explanationNarrative': 'High burnout risk (99%). The risk is driven primarily by high workload / resource demand '
                          'and seniority level. Recommended: a confidential wellbeing check-in and a workload review '
                          'this cycle.',
  'recommendedAction': 'Recommended: a confidential wellbeing check-in and a workload review this cycle.'},
 {'employeeId': 'E10047',
  'department': 'Sales',
  'jobTitle': 'Sales Representative',
  'sapFields': {'perPersonal.gender': 'Male',
                'perPerson.age': 25,
                'empJob.department': 'Sales',
                'empJob.jobTitle': 'Sales Representative',
                'empJob.payGrade': 1,
                'timeManagement.overtimeFlag': 0,
                'empPayCompRecurring.monthlyIncome': 4400,
                'empEmployment.yearsAtCompany': 3},
  'riskScores': {'burnout': 0.999, 'mentalHealth': 0.997, 'attrition': 0.653},
  'cbri': 0.929,
  'riskLevel': 'High',
  'topFactors': [{'factor': 'high workload / resource demand', 'direction': 'increases'},
                 {'factor': 'workload relative to seniority', 'direction': 'increases'},
                 {'factor': 'no work-from-home option', 'direction': 'increases'}],
  'explanationNarrative': 'High burnout risk (100%). The risk is driven primarily by high workload / resource demand '
                          'and workload relative to seniority. Recommended: a confidential wellbeing check-in and a '
                          'workload review this cycle.',
  'recommendedAction': 'Recommended: a confidential wellbeing check-in and a workload review this cycle.'},
 {'employeeId': 'E10048',
  'department': 'Sales',
  'jobTitle': 'Sales Executive',
  'sapFields': {'perPersonal.gender': 'Female',
                'perPerson.age': 24,
                'empJob.department': 'Sales',
                'empJob.jobTitle': 'Sales Executive',
                'empJob.payGrade': 2,
                'timeManagement.overtimeFlag': 0,
                'empPayCompRecurring.monthlyIncome': 4577,
                'empEmployment.yearsAtCompany': 2},
  'riskScores': {'burnout': 0.998, 'mentalHealth': 0.993, 'attrition': 0.645},
  'cbri': 0.926,
  'riskLevel': 'High',
  'topFactors': [{'factor': 'high workload / resource demand', 'direction': 'increases'},
                 {'factor': 'seniority level', 'direction': 'increases'},
                 {'factor': 'no work-from-home option', 'direction': 'increases'}],
  'explanationNarrative': 'High burnout risk (100%). The risk is driven primarily by high workload / resource demand '
                          'and seniority level. Recommended: a confidential wellbeing check-in and a workload review '
                          'this cycle.',
  'recommendedAction': 'Recommended: a confidential wellbeing check-in and a workload review this cycle.'},
 {'employeeId': 'E10049',
  'department': 'Research & Development',
  'jobTitle': 'Laboratory Technician',
  'sapFields': {'perPersonal.gender': 'Male',
                'perPerson.age': 41,
                'empJob.department': 'Research & Development',
                'empJob.jobTitle': 'Laboratory Technician',
                'empJob.payGrade': 1,
                'timeManagement.overtimeFlag': 1,
                'empPayCompRecurring.monthlyIncome': 4721,
                'empEmployment.yearsAtCompany': 18},
  'riskScores': {'burnout': 0.998, 'mentalHealth': 0.994, 'attrition': 0.48},
  'cbri': 0.893,
  'riskLevel': 'High',
  'topFactors': [{'factor': 'high workload / resource demand', 'direction': 'increases'},
                 {'factor': 'workload relative to seniority', 'direction': 'increases'},
                 {'factor': 'work-from-home available', 'direction': 'increases'}],
  'explanationNarrative': 'High burnout risk (100%). The risk is driven primarily by high workload / resource demand '
                          'and workload relative to seniority. Recommended: a confidential wellbeing check-in and a '
                          'workload review this cycle.',
  'recommendedAction': 'Recommended: a confidential wellbeing check-in and a workload review this cycle.'}]
